/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "computations.h"
#include <stdio.h>


/* addition function */
float *
addition_1_svc(operation_operands *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("\n");
	printf("	+----------------------------+\n");
	printf("	|     Server Operation       |\n");
	printf("	+----------------------------+\n");
	printf("	|    Addition in progress..  |\n");
	printf("	+----------------------------+\n");
	printf("\n");

	result=argp->num1 + argp->num2;

	printf("	+----------------------------+\n");
	printf("            Result calculated     \n");
	printf("	+----------------------------+\n");
	printf("\n");

	return &result;
}

/* subtraction function  */
float *
subtruction_1_svc(operation_operands *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("\n");
	printf("	+----------------------------+\n");
	printf("	|     Server Operation       |\n");
	printf("	+----------------------------+\n");
	printf("	|  Subtruction in progress.. |\n");
	printf("	+----------------------------+\n");
	printf("\n");

	result=argp->num1 - argp->num2;

	printf("	+----------------------------+\n");
	printf("           Result calculated      \n");
	printf("	+----------------------------+\n");
	printf("\n");

	return &result;

}


/* multiplaction function*/
float *
multiplication_1_svc(operation_operands *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("\n");
	printf("	+-------------------------------+\n");
	printf("	|       Server Operation        |\n");
	printf("	+-------------------------------+\n");
	printf("	|  Multiplication in progress.. |\n");
	printf("	+-------------------------------+\n");
	printf("\n");

	result= argp->num1 * argp->num2;

	printf("	+------------------------------+\n");
	printf("           Result calculated      \n");
	printf("	+------------------------------+\n");
	printf("\n");

	return &result;

}

/* division function */
float *
division_1_svc(operation_operands *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("\n");
	printf("	+----------------------------+\n");
	printf("	|     Server Operation       |\n");
	printf("	+----------------------------+\n");
	printf("	|    Dision in progress..    |\n");
	printf("	+----------------------------+\n");
	printf("\n");

	result=(argp->num1)/(argp->num2);

	printf("	+---------------------------+\n");
	printf("            Result calculated   \n");
	printf("	+---------------------------+\n");
	printf("\n");

	return &result;
}
