/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "computations.h"

bool_t
xdr_operation_operands (XDR *xdrs, operation_operands *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->num2))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->operation))
		 return FALSE;
	return TRUE;
}
