/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "computations.h"
#include <stdio.h>


float
computation_1(char *host, float a, float b, char op)
{
	CLIENT *clnt;
	float  *result_1;
	operation_operands  addition_1_arg;
	float  *result_2;
	operation_operands  subtruction_1_arg;
	float  *result_3;
	operation_operands  multiplication_1_arg;
	float  *result_4;
	operation_operands  division_1_arg;

	if(op=='+'){

		addition_1_arg.num1=a;
		addition_1_arg.num2=b;
		addition_1_arg.operation=op;

		clnt=clnt_create(host, computation, compuation_version, "udp");
		if (clnt==NULL){
			clnt_pcreateerror(host);
			exit(1);
		}

		result_1 = addition_1(&addition_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		clnt_destroy(clnt);

		return (*result_1);

	}else if(op=='-'){

		subtruction_1_arg.num1=a;
		subtruction_1_arg.num2=b;
		subtruction_1_arg.operation=op;

		clnt=clnt_create(host, computation, compuation_version, "udp");
		if (clnt==NULL){
			clnt_pcreateerror(host);
			exit(1);
		}

		result_2 = subtruction_1(&subtruction_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		clnt_destroy(clnt);
		return (*result_2);

	}else if(op=='*'){

		multiplication_1_arg.num1=a;
		multiplication_1_arg.num2=b;
		multiplication_1_arg.operation=op;

		clnt=clnt_create(host, computation, compuation_version, "udp");
		if (clnt==NULL){
			clnt_pcreateerror(host);
			exit(1);
		}

		result_3 = multiplication_1(&multiplication_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		clnt_destroy(clnt);
		return (*result_3);

	}else if(op=='/'){

		if(b==0)
		{
			printf("+---------------------------------+\n");
			printf("|         Error Handler           |\n");
			printf("+---------------------------------+\n");
			printf("|    The divisor cannot be 0      |\n");
			printf("+---------------------------------+\n");

			exit(1);

		}
		else{

			division_1_arg.num1=a;
			division_1_arg.num2=b;
			division_1_arg.operation=op;

			clnt=clnt_create(host, computation, compuation_version, "udp");
			if (clnt==NULL){
				clnt_pcreateerror(host);
				exit(1);
			}

			result_4 = division_1(&division_1_arg, clnt);
			if (result_4 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			return (*result_4);
		}
	}
	else{

			printf("+---------------------------------+\n");
			printf("|         Error Handler           |\n");
			printf("+---------------------------------+\n");
			printf("|      Invalid Operator   !!      |\n");
			printf("+---------------------------------+\n");

			exit(1);
	}

}



int
main (int argc, char *argv[])
{
	char *host, operator;
	float number1, number2, result;


	/*request for server ip if not provided on running the client*/
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];

	/*get the first number*/
	printf("Enter the first number:");
	scanf("%f", &number1);

	/*get the second number*/
	printf("Enter the second number:");
	scanf("%f", &number2);

	/*get the operator*/
	printf("Enter the operator(+,-,/,*):");
	scanf("%s", &operator);


	printf("\n");
	printf("+---------------------------------+\n");
	printf("|     Computation Result          |\n");
	printf("|---------------------------------|\n");
	printf("    %.1f %s %.1f = %.2f                    \n",number1, &operator,number2, computation_1 (host, number1, number2, operator));
	printf("+---------------------------------+\n");
	printf("\n");
exit (0);
}
