/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMPUTATIONS_H_RPCGEN
#define _COMPUTATIONS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operation_operands {
	float num1;
	float num2;
	char operation;
};
typedef struct operation_operands operation_operands;

#define computation 45784512
#define compuation_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define addition 1
extern  float * addition_1(operation_operands *, CLIENT *);
extern  float * addition_1_svc(operation_operands *, struct svc_req *);
#define subtruction 2
extern  float * subtruction_1(operation_operands *, CLIENT *);
extern  float * subtruction_1_svc(operation_operands *, struct svc_req *);
#define multiplication 3
extern  float * multiplication_1(operation_operands *, CLIENT *);
extern  float * multiplication_1_svc(operation_operands *, struct svc_req *);
#define division 4
extern  float * division_1(operation_operands *, CLIENT *);
extern  float * division_1_svc(operation_operands *, struct svc_req *);
extern int computation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addition 1
extern  float * addition_1();
extern  float * addition_1_svc();
#define subtruction 2
extern  float * subtruction_1();
extern  float * subtruction_1_svc();
#define multiplication 3
extern  float * multiplication_1();
extern  float * multiplication_1_svc();
#define division 4
extern  float * division_1();
extern  float * division_1_svc();
extern int computation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation_operands (XDR *, operation_operands*);

#else /* K&R C */
extern bool_t xdr_operation_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMPUTATIONS_H_RPCGEN */
